spring:
  application:
    name: sales
  datasource:
    url: jdbc:h2:mem:saleDb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
vehicle:
  service:
    url: http://localhost:8081/veiculos